FROM alpine:latest

#Update and install openssh
RUN apk update
RUN apk add openssh

#Change root Passwort or remove
RUN echo "root:|ichbineinpasswort|" | chpasswd
#RUN passwd -d root

#Add User
RUN adduser user -D
RUN echo "user:|ichbineinpasswort|" | chpasswd
#Add Public Key for user
COPY identitys/identity.pub /home/user/.ssh/autorized_keys

#Add second User 
#RUN adduser user2 -D
#RUN echo "user:|ichbineinpasswort|" | chpasswd
#Add Public Key for second user
#COPY identitys/identity2.pub /home/user2/.ssh/autorized_keys


#sshd_config 
COPY sshd-files/* /etc/ssh/

#Copy Host-Keys
COPY hostkey/* /etc/ssh/

#Run openssh
#ENTRYPOINT ["/entrypoint.sh"]
#COPY entrypoint.sh /

#Start openssh server
CMD ["/usr/sbin/sshd", "-D"]

#Open Ports
EXPOSE 22
