
version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
      - /etc/timezone:/etc/timezone:ro
    environment:
      EULA: "TRUE"
    env_file:
      - ./minecraft.env  
    restart: always

