version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  nextcloud:
    image: nextcloud
    restart: always
    expose:
      - 80
    volumes:
      - nextcloud:/var/www/html
      - ./maxfilesize:/usr/local/etc/php/php.ini
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - VIRTUAL_HOST=cloud.example.net
      - LETSENCRYPT_HOST=cloud.example.net
      - LETSENCRYPT_EMAIL=info@example.net
      - TRUSTED_PROXIES=['127.0.0.1']
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.examplezwickel.net
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

volumes:
  db:
  nextcloud:

networks:
    default:
        external:
            name: nginx-proxy

secrets:
  nextcloud_admin_password:
    file: ./nextcloud_admin_password # put admin password to this file
  nextcloud_admin_user:
    file: ./nextcloud_admin_user # put admin username to this file
  postgres_db:
    file: ./postgres_db # put postgresql db name to this file
  postgres_password:
    file: ./postgres_password # put postgresql password to this file
  postgres_user:
    file: ./postgres_user # put postgresql username to this file


