FROM alpine:latest

#Update and install openssh
RUN apk update
RUN apk add openssh

#Change root Passwort or remove
RUN echo "root:|ichbineinpasswort|" | chpasswd
#RUN passwd -d root

#Add User
RUN adduser user -D
RUN echo "user:|ichbineinpasswort|" | chpasswd
#Add Public Key for user
COPY identitys/identity.pub /home/user/.ssh/authorized_keys
RUN chown -R user:user /home/user/.ssh
RUN chmod 700 /home/user/.ssh
RUN chmod 644 /home/user/.ssh/authorized_keys

#Add second User 
#RUN adduser user2 -D
#RUN echo "user:|ichbineinpasswort|" | chpasswd
#Add Public Key for second user
#COPY identitys/identity2.pub /home/user2/.ssh/authorized_keys
#RUN chown -R user2:user2 /home/user2/.ssh
#RUN chmod 700 /home/user2/.ssh
#RUN chmod 600 /home/user/.ssh/authorized_keys

#Copy Host-Keys
COPY hostkey/* /etc/ssh/
RUN chmod 700 /etc/ssh/*

#ssh_config ssh-banner ssh not sshd in alpine
COPY ssh-files/s* /etc/ssh/

#Open Ports
EXPOSE 22

#Start openssh server
CMD ["/usr/sbin/sshd", "-D"]

